### ISSUE TITLE
Translate README into English

### ISSUE THREAD

**Issue by TamaWilson** [TamaWilson/mybatis-query-builder#2]
Need translation to README file.

**Comment by 96RadhikaJadhav** [comment]
@TamaWilson Can I work on the issue?

**Comment by TamaWilson** [comment]
@96RadhikaJadhav sure. The initial readme is a bit vague, so if you need more context you can see my example project at [this repository ](https://github.com/TamaWilson/my-batis-query-builder-example) and feel free to ask me anything.
